name: task_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  material_symbols_icons: ^4.2800.2
  icons_plus: ^5.0.0
  syncfusion_flutter_calendar: ^28.1.35
  syncfusion_flutter_datepicker: ^28.1.35
  #   syncfusion_flutter_calendar: ^27.2.4
  # syncfusion_flutter_datepicker: ^27.2.5
  buttons_tabbar: ^1.3.12
  dropdown_button2: ^2.3.9
  fl_chart: ^0.69.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3
  custom_radio_group_list: ^1.1.2
  supabase_flutter: ^2.8.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
