name: task_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  material_symbols_icons: ^4.2800.2
  icons_plus: ^5.0.0
  syncfusion_flutter_calendar: ^27.2.4
  buttons_tabbar: ^1.3.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
