// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2qyG7nKjjTtRA1i1YkG7M5IrRBvmWgM',
    appId: '1:369327109932:web:5185761eeb5072c0319e89',
    messagingSenderId: '369327109932',
    projectId: 'firertdb-bb50f',
    authDomain: 'firertdb-bb50f.firebaseapp.com',
    databaseURL: 'https://firertdb-bb50f-default-rtdb.firebaseio.com',
    storageBucket: 'firertdb-bb50f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3kBOl6xhrPaKs01Q-TqpXcv30Ubno_Q',
    appId: '1:369327109932:android:cfdcc88a0789da2a319e89',
    messagingSenderId: '369327109932',
    projectId: 'firertdb-bb50f',
    databaseURL: 'https://firertdb-bb50f-default-rtdb.firebaseio.com',
    storageBucket: 'firertdb-bb50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArY64l_WHZv0P2hqSAW6HUDiec9X46u1Q',
    appId: '1:369327109932:ios:0c5ac5547a1106da319e89',
    messagingSenderId: '369327109932',
    projectId: 'firertdb-bb50f',
    databaseURL: 'https://firertdb-bb50f-default-rtdb.firebaseio.com',
    storageBucket: 'firertdb-bb50f.firebasestorage.app',
    androidClientId: '369327109932-nafjdrj11e76fbsdqgjpqtusq68e29ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
